# Generated by Django 2.2.12 on 2020-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0035_offerassignmentemailtemplates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerassignmentemailtemplates',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
